//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atAcc.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class crm_iktisadEntities : DbContext
    {
        public crm_iktisadEntities()
            : base("name=crm_iktisadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_accountGroupDtls> tbl_accountGroupDtls { get; set; }
        public virtual DbSet<tbl_accountLedgerDtls> tbl_accountLedgerDtls { get; set; }
        public virtual DbSet<tbl_budget> tbl_budget { get; set; }
        public virtual DbSet<tbl_creditDebitCard> tbl_creditDebitCard { get; set; }
        public virtual DbSet<tbl_person> tbl_person { get; set; }
        public virtual DbSet<tbl_project> tbl_project { get; set; }
        public virtual DbSet<tbl_service> tbl_service { get; set; }
        public virtual DbSet<tbl_vehicle> tbl_vehicle { get; set; }
        public virtual DbSet<tbl_wareHouse> tbl_wareHouse { get; set; }
        public virtual DbSet<tbl_login> tbl_login { get; set; }
        public virtual DbSet<tbl_employeeDtls> tbl_employeeDtls { get; set; }
        public virtual DbSet<tbl_productGroupDetails> tbl_productGroupDetails { get; set; }
        public virtual DbSet<tbl_companyDetails> tbl_companyDetails { get; set; }
        public virtual DbSet<tbl_rackInfo> tbl_rackInfo { get; set; }
        public virtual DbSet<tbl_invoice> tbl_invoice { get; set; }
        public virtual DbSet<tbl_salesInvoice> tbl_salesInvoice { get; set; }
        public virtual DbSet<tbl_purchaseInvoice> tbl_purchaseInvoice { get; set; }
        public virtual DbSet<tbl_taxInfo> tbl_taxInfo { get; set; }
        public virtual DbSet<tbl_productDtls> tbl_productDtls { get; set; }
        public virtual DbSet<tbl_custominvoice> tbl_custominvoice { get; set; }
        public virtual DbSet<tbl_accountMoreDtls> tbl_accountMoreDtls { get; set; }
    }
}
