//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atAcc.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_companyDetails
    {
        public int id { get; set; }
        public string comp_id { get; set; }
        public string comp_name { get; set; }
        public string comp_url { get; set; }
        public string comp_addr { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postal_code { get; set; }
        public string tel_no { get; set; }
        public string comp_email { get; set; }
        public string mob_no { get; set; }
        public string comp_fax { get; set; }
        public string comp_site { get; set; }
        public string acc_no { get; set; }
        public string currency { get; set; }
        public string tax { get; set; }
        public string vat_no { get; set; }
        public string vat_pswd { get; set; }
    }
}
