//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atAcc.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vehicle
    {
        public int id { get; set; }
        public string vehicle_name { get; set; }
        public string vehicle_no { get; set; }
        public string description { get; set; }
        public string contact_person { get; set; }
        public Nullable<long> mob_no { get; set; }
    }
}
