//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atAcc.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_productDtls
    {
        public int id { get; set; }
        public string product_code { get; set; }
        public string product_name { get; set; }
        public string product_namearabic { get; set; }
        public string product_group { get; set; }
        public string product_color { get; set; }
        public Nullable<int> base_unit { get; set; }
        public Nullable<int> rack_id { get; set; }
        public Nullable<int> tax_type { get; set; }
        public Nullable<int> quantity { get; set; }
        public string description { get; set; }
        public int hsn_code { get; set; }
        public string minimum { get; set; }
        public string reorder { get; set; }
        public string maximum { get; set; }
        public Nullable<int> purchase_rate { get; set; }
        public Nullable<int> sales_rate { get; set; }
        public Nullable<int> sales_percent { get; set; }
        public Nullable<int> mrp { get; set; }
        public Nullable<int> min_salesrate { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
