//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atAcc.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_custominvoice
    {
        public int id { get; set; }
        public string party_vno { get; set; }
        public string invoice_id { get; set; }
        public string party_name { get; set; }
        public string party_namearabic { get; set; }
    }
}
