//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atAcc.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_budget
    {
        public int id { get; set; }
        public string budget_name { get; set; }
        public Nullable<System.DateTime> start_from { get; set; }
        public Nullable<System.DateTime> up_to { get; set; }
        public Nullable<long> account { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> allocate_tot { get; set; }
    }
}
