//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atAcc.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoice
    {
        public int id { get; set; }
        public string invoice_id { get; set; }
        public string voucher { get; set; }
        public string cash_party_acc { get; set; }
        public string type { get; set; }
        public string acc_id { get; set; }
        public string remarks { get; set; }
        public string depot_loc { get; set; }
        public string purchase_acc { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string party_vno { get; set; }
        public string spl_disc { get; set; }
        public string gst { get; set; }
        public string addl_per { get; set; }
        public string invoice_type { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string tot_qty { get; set; }
        public string tot_gross { get; set; }
        public string tot_net { get; set; }
        public string voucherArabic { get; set; }
        public string dateArabic { get; set; }
    }
}
