//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atAcc.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_accountLedgerDtls
    {
        public int id { get; set; }
        public Nullable<int> grp_id { get; set; }
        public Nullable<int> ledger_code { get; set; }
        public string ledger_name { get; set; }
        public string under { get; set; }
        public Nullable<int> discount { get; set; }
    }
}
