//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atAcc.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_accountMoreDtls
    {
        public int id { get; set; }
        public Nullable<int> grp_id { get; set; }
        public string contact_person { get; set; }
        public string contact_personArabic { get; set; }
        public string addr1 { get; set; }
        public string addr1Arabic { get; set; }
        public string addr2 { get; set; }
        public string addr2Arabic { get; set; }
        public string city { get; set; }
        public string cityArabic { get; set; }
        public string postal_code { get; set; }
        public string tel_no { get; set; }
        public string acc_id { get; set; }
        public string mob_no { get; set; }
        public string email { get; set; }
        public string vat_no { get; set; }
        public string tax_no { get; set; }
        public string gst_no { get; set; }
        public string state { get; set; }
        public string state_code { get; set; }
        public string ledger_id { get; set; }
    }
}
