//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atAcc.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_productGroupDetails
    {
        public int id { get; set; }
        public string hsn_code { get; set; }
        public string group_name { get; set; }
        public string group_head { get; set; }
        public Nullable<int> stock_status { get; set; }
        public string created_at { get; set; }
        public string updated_at { get; set; }
    }
}
