//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atAcc.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_wareHouse
    {
        public int id { get; set; }
        public string depot_name { get; set; }
        public string address { get; set; }
        public string under_depo { get; set; }
        public Nullable<int> postal_code { get; set; }
        public string city { get; set; }
        public Nullable<long> mob_no { get; set; }
        public Nullable<long> tel_no { get; set; }
        public Nullable<int> reg_no { get; set; }
        public string contact_person { get; set; }
        public string description { get; set; }
        public Nullable<long> licence_no { get; set; }
    }
}
