//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atAcc.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_purchaseInvoice
    {
        public int id { get; set; }
        public string invoice_id { get; set; }
        public string code { get; set; }
        public string product_name { get; set; }
        public string quantity { get; set; }
        public string rate { get; set; }
        public string amount { get; set; }
        public string spl_per { get; set; }
        public string spl_disc { get; set; }
        public string addl_disc { get; set; }
        public string total_tax { get; set; }
        public string net_amt { get; set; }
        public string gst_per { get; set; }
        public string discount { get; set; }
        public string gst { get; set; }
        public string mrp { get; set; }
        public string sticker_qty { get; set; }
        public string imeno { get; set; }
    }
}
